# Generated by Django 3.2.7 on 2022-11-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20221116_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='rank',
        ),
        migrations.AlterField(
            model_name='member',
            name='rank',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='tags',
            name='question',
        ),
        migrations.AddField(
            model_name='tags',
            name='question',
            field=models.ManyToManyField(related_name='tags', related_query_name='tag', to='app.Question'),
        ),
    ]
