# Generated by Django 3.2.7 on 2022-12-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20221116_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_tags',
            field=models.CharField(default='some tags', max_length=100),
        ),
    ]
