# Generated by Django 3.2.7 on 2022-12-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_question_question_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_tags',
            field=models.CharField(default='', max_length=100),
        ),
    ]
